USE DATABASE horarios;

CREATE TABLE profesor (
  idprofesor INT NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  rol INT NOT NULL,
  contrasena VARCHAR(8) NOT NULL,
  PRIMARY KEY (idprofesor));


CREATE TABLE materias (
  clave_materia VARCHAR(7) NOT NULL,
  clave_carrera VARCHAR(3) NOT NULL,
  materia VARCHAR(55) NOT NULL,
  carrera VARCHAR(40) NOT NULL,
  periodo VARCHAR(21) NOT NULL,
  turno VARCHAR(8) NOT NULL,
  semestre INT NOT NULL,
  creditos INT NOT NULL,
  h_teoricas INT NOT NULL,
  h_practicas INT NOT NULL,
  PRIMARY KEY (clave_materia));
  

  
 CREATE TABLE horario (
  clave_horario INT NOT NULL AUTO_INCREMENT,
  clave_materia VARCHAR(7) NOT NULL,
  idprofesor INT NULL,
  grupo VARCHAR(2) NOT NULL,
  no_alum INT NOT NULL,
  salon VARCHAR(4) NOT NULL,
  lunes VARCHAR(11) NULL,
  martes VARCHAR(11) NULL,
  miercoles VARCHAR(11) NULL,
  jueves VARCHAR(11) NULL,
  viernes VARCHAR(11) NULL,
  PRIMARY KEY (clave_horario)
  FOREIGN KEY(clave_materia) REFERENCES materias (clave_materia)
  FOREIGN KEY(idprofesor) REFERENCES profesor (idprofesor));
  
  
INSERT INTO materias VALUES ( "ACF0901", "ISX", "CÁLCULO DIFERENCIAL", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 1,5,3,2);
INSERT INTO materias VALUES ( "AED1285", "ISX", "FUNDAMENTOS DE PROGRAMACIÓN", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 1,5,2,3);
INSERT INTO materias VALUES ( "AEF1041", "ISX", "MATEMÁTICAS DISCRETAS", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 1,5,0,4);
INSERT INTO materias VALUES ( "SCH1024", "ISX", "TALLER DE ADMINISTRACIÓN", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 1,4,3,2);
INSERT INTO materias VALUES ( "ACC0906", "ISX", "FUNDAMENTOS DE INVESTIGACIÓN", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 1,4,2,2);
INSERT INTO materias VALUES ( "ACA0907", "ISX", "TALLER DE ÉTICA", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 1,4,1,3);
INSERT INTO materias VALUES ( "ACF0902", "ISX", "CÁLCULO INTEGRAL", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 2,5,3,2);
INSERT INTO materias VALUES ( "ACF0903", "ISX", "ÁLGEBRA LINEAL", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 2,5,3,2);
INSERT INTO materias VALUES ( "AED1286", "ISX", "PROGRAMACIÓN ORIENTADA A OBJETOS", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 2,5,2,3);
INSERT INTO materias VALUES ( "AEC1008", "ISX", "CONTABILIDAD FINANCIERA", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 2,4,2,2);
INSERT INTO materias VALUES ( "AEC1058", "ISX", "QUÍMICA", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 2,4,2,2);
INSERT INTO materias VALUES ( "AEF1052", "ISX", "PROBABILIDAD Y ESTADÍSTICA", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 2,5,3,2);
INSERT INTO materias VALUES ( "ACF0904", "ISX", "CÁLCULO VECTORIAL", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 3,5,3,2);
INSERT INTO materias VALUES ( "AED1026", "ISX", "ESTRUCTURA DE DATOS", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 3,5,2,3);
INSERT INTO materias VALUES ( "SCF1006", "ISX", "FÍSICA GENERAL", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 3,5,3,2);
INSERT INTO materias VALUES ( "SCC1013", "ISX", "INVESTIGACIÓN DE OPERACIONES", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 3,4,2,2);
INSERT INTO materias VALUES ( "SCC1005", "ISX", "CULTURA EMPRESARIAL", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 3,4,2,2);
INSERT INTO materias VALUES ( "ACD0908", "ISX", "DESARROLLO SUSTENTABLE", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 3,5,2,3);
INSERT INTO materias VALUES ( "ACF0905", "ISX", "ECUACIONES DIFERENCIALES", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 4,5,3,2);
INSERT INTO materias VALUES ( "SCD1027", "ISX", "TÓPICOS AVANZADOS DE PROGRAMACIÓN", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 4,5,2,3);
INSERT INTO materias VALUES ( "SCD1018", "ISX", "PRINCIPIOS ELÉCTRICOS Y APLICACIONES DIGITALES", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 4,5,2,3);
INSERT INTO materias VALUES ( "AEF1031", "ISX", "FUNDAMENTOS DE BASE DE DATOS", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 4,5,3,2);
INSERT INTO materias VALUES ( "SCD1022", "ISX", "SIMULACIÓN", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 4,5,2,3);
INSERT INTO materias VALUES ( "SCC1017", "ISX", "MÉTODOS NUMÉRICOS", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 4,4,2,2);
INSERT INTO materias VALUES ( "SCD1003", "ISX", "ARQUITECTURA DE COMPUTADORAS", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 5,5,2,3);
INSERT INTO materias VALUES ( "SCA1025", "ISX", "TALLER DE BASE DE DATOS", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 5,4,0,4);
INSERT INTO materias VALUES ( "SCC1010", "ISX", "GRAFICACIÓN", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 5,4,2,2);
INSERT INTO materias VALUES ( "AEC1034", "ISX", "FUNDAMENTOS DE TELECOMUNICACIONES", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 5,4,2,2);
INSERT INTO materias VALUES ( "SCC1007", "ISX", "FUNDAMENTOS DE INGENIERÍA DE SOFTWARE", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 5,4,2,2);
INSERT INTO materias VALUES ( "AEC1061", "ISX", "SISTEMAS OPERATIVOS", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 5,4,2,2);
INSERT INTO materias VALUES ( "SCC1014", "ISX", "LENGUAJES DE INTERFAZ", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 6,4,2,2);
INSERT INTO materias VALUES ( "SCB1001", "ISX", "ADMINISTRACIÓN DE BASE DE DATOS", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 6,5,1,4);
INSERT INTO materias VALUES ( "SCD1021", "ISX", "REDES DE COMPUTADORAS", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 6,5,2,3);
INSERT INTO materias VALUES ( "SCA1026", "ISX", "TALLER DE SISTEMAS OPERATIVOS", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 6,4,0,4);
INSERT INTO materias VALUES ( "SCD1011", "ISX", "INGENIERÍA DE SOFTWARE", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 6,5,2,3);
INSERT INTO materias VALUES ( "SCD1015", "ISX", "LENGUAJES Y AUTÓMATAS I", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 6,5,2,3);
INSERT INTO materias VALUES ( "SCC1023", "ISX", "SISTEMAS PROGRAMABLES", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 7,4,2,2);
INSERT INTO materias VALUES ( "DAD1401", "ISX", "BASES DE DATOS AVANZADAS", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 7,5,2,3);
INSERT INTO materias VALUES ( "SCD1004", "ISX", "CONMUTACIÓN Y ENRUTAMIENTO EN REDES DE DATOS", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 7,5,2,3);
INSERT INTO materias VALUES ( "SCG1009", "ISX", "GESTIÓN DE PROYECTOS DE SOFTWARE", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 7,6,3,3);
INSERT INTO materias VALUES ( "SCD1016", "ISX", "LENGUAJES Y AUTÓMATAS II", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 7,5,2,3);
INSERT INTO materias VALUES ( "ACA0909", "ISX", "TALLER DE INVESTIGACIÓN I", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 7,4,0,4);
INSERT INTO materias VALUES ( "SCA1002", "ISX", "ADMINISTRACIÓN DE REDES", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 8,4,0,4);
INSERT INTO materias VALUES ( "ACA0910", "ISX", "TALLER DE INVESTIGACIÓN II", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 8,4,0,4);
INSERT INTO materias VALUES ( "SCC1019", "ISX", "PROGRAMACIÓN LÓGICA Y FUNCIONAL", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 8,4,2,2);
INSERT INTO materias VALUES ( "AEB1055", "ISX", "PROGRAMACIÓN WEB", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 8,5,1,4);
INSERT INTO materias VALUES ( "DAD1402", "ISX", "DESARROLLO DE APLICACIONES EMPRESARIALES", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 8,5,2,3);
INSERT INTO materias VALUES ( "SCC1012", "ISX", "INTELIGENCIA ARTIFICIAL", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 9,4,2,2);
INSERT INTO materias VALUES ( "DAD1403", "ISX", "PROGRAMACIÓN WEB AVANZADA", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 9,5,2,3);
INSERT INTO materias VALUES ( "DAD1404", "ISX", "ARQUITECTURA DE APLICACIONES EMPRESARIALES", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 9,5,2,3);
INSERT INTO materias VALUES ( "DAB1405", "ISX", "DESARROLLO DE APLICACIONES PARA DISPOSITIVOS MÓVILES", "INGENIERÍA EN SISTEMAS COMPUTACIONALES", "AGOSTO-DICIEMBRE/2020", "MATUTINO", 9,5,2,3);

    
INSERT INTO profesor VALUES (24501,"ING. SAEZ DE NANCLARES RODRIGUEZ RUTH", 2, "P24501");
INSERT INTO profesor VALUES (24502,"ING HERNÁNDEZ RODRÍGUEZ JOSÉ FERNANDO", 2, "P24502");
INSERT INTO profesor VALUES (24503,"ING. MARTINEZ TREJO DENY", 2, "P24503");
INSERT INTO profesor VALUES (24504,"ING. BERMUDEZ GUADALUPE EFRAIN", 2, "P24504");
INSERT INTO profesor VALUES (24505,"ING. CARPIO FLORES JOSE GERARDO", 2, "P24505");
INSERT INTO profesor VALUES (24506,"ING. AGUILA REYES ANTONIO", 1, "P24506");
INSERT INTO profesor VALUES (24507,"ING. GUTIERREZ AYALA LUIS EDUARDO", 2, "P24507");
INSERT INTO profesor VALUES (24508,"ING SAUCEDO TORRES MARÍA MINERVA", 2, "P24508");
INSERT INTO profesor VALUES (24509,"ING. GALVAN JARAMILLO PAOLA VIRGINIA", 2, "P24509");
INSERT INTO profesor VALUES (24510,"ING. RODRIGUEZ RENTERIA JOSE ALEJANDRO", 2, "P24510");
INSERT INTO profesor VALUES (24511,"LIC. RAMIREZ ALVAREZ IRMA DE JESUS", 2, "P24511");
INSERT INTO profesor VALUES (24512,"ING. MARTINEZ AGUILAR ANA COLUMBA ZURITA", 2, "P24512");
INSERT INTO profesor VALUES (24513,"ING. MARTINEZ ARIAS JOSE ELIAS", 2, "P24513");
INSERT INTO profesor VALUES (24514,"ING. GUEVARA RANGEL LAURA PATRICIA", 2, "P24514");
INSERT INTO profesor VALUES (24515,"LIC. MORENO REAL ROXANA NOEMI", 2, "P24515");
INSERT INTO profesor VALUES (24516,"ING. MARIN GONZALEZ EUGENIO CONRADO", 2, "P24516");
INSERT INTO profesor VALUES (24517,"ING VIGUERAS MONTAÑO IVAN", 2, "P24517");
INSERT INTO profesor VALUES (24518,"ING. GARCIA TRUJILLO ALEJANDRO", 2, "P24518");
INSERT INTO profesor VALUES (24519,"ING. MEDINA LÓPEZ DENISSE", 2, "P24519");
INSERT INTO profesor VALUES (24520,"LIC. CASTELLANOS NOLASCO ELIZABETH", 2, "P24520");
INSERT INTO profesor VALUES (24521,"ING. TRUJILLO CORONA RUBEN", 2, "P24521");
INSERT INTO profesor VALUES (24522,"M.C. ROCHA SANCHEZ MARTHA ALICIA", 2, "P24522");
INSERT INTO profesor VALUES (24523,"ING. GODINEZ CABRERA HECTOR FEDERICO", 2, "P24523");
INSERT INTO profesor VALUES (24524,"ING. GUIZAR RUIZ JUAN IGNACIO", 2, "P24524");
INSERT INTO profesor VALUES (24525,"ING. RUIZ GAYTAN LUZ DEL CARMEN", 2, "P24525");
INSERT INTO profesor VALUES (24526,"ING. SILVA TOVAR CIRINO", 2, "P24526");
INSERT INTO profesor VALUES (24527,"ING. ORNELAS RODRIGUEZ MANUEL", 2, "P24527");
INSERT INTO profesor VALUES (24528,"DR. MOSIÑO JUAN FRANCISCO", 2, "P24528");
INSERT INTO profesor VALUES (24529,"ING MORALES REYES OSCAR ANDRES", 2, "P24529");
INSERT INTO profesor VALUES (24530,"MTRA PÉREZ FLORES ANGÉLICA JOSEFINA", 2, "P24530");
INSERT INTO profesor VALUES (24531,"MTRA SÁNCHEZ CANO MA. CONCEPCIÓN ROCÍO", 2, "P24531");
INSERT INTO profesor VALUES (24532,"LIC RODRÍGUEZ MUÑOZ GUSTAVO ADOLFO", 2, "P24532");
INSERT INTO profesor VALUES (24533,"LIC. ORTIZ GAUCIN ANGELICA MARIA", 2, "P24533");
INSERT INTO profesor VALUES (24534,"LIC. LUGO PEDROZA DAVID EVERARDO", 2, "P24534");
INSERT INTO profesor VALUES (24535,"LIC. PUGA SOBERANES HECTOR JOSE", 2, "P24535");
INSERT INTO profesor VALUES (24536,"ING. GASCA GONZALEZ JOSE ALFREDO", 2, "P24536");
INSERT INTO profesor VALUES (24537,"ING. LEVY ROJAS CARLOS RAFAEL", 2, "J24537");
INSERT INTO profesor VALUES (24538,"ING. PEREZ PINTOR EDUARDO JOSE", 2, "P24538");
INSERT INTO profesor VALUES (24539,"DRA BALTAZAR FLORES MARIA DEL ROSARIO", 2, "P24539");
INSERT INTO profesor VALUES (24540,"ING. JUAREZ GUERRA LAURA", 2, "P24540");
INSERT INTO profesor VALUES (24541,"DR. CARPIO VALADEZ JUAN MARTIN", 2, "P24541");
INSERT INTO profesor VALUES (24542,"ING. ARELLANO VERA MARIA DE LOS ANGELES", 2, "P24542");
INSERT INTO profesor VALUES (24543,"ING. HERNANDEZ CARRANZA ANGELICA BENITA", 2, "P24543");
INSERT INTO profesor VALUES (24544,"ING PEÑA LÓPEZ MIGUEL ÁNGEL", 2, "P24544");
INSERT INTO profesor VALUES (24545,"DR. SANTIAGO MONTERO RAÚL", 2, "P24545");
INSERT INTO profesor VALUES (24546,"DR. ZAMUDIO RODRIGUEZ VICTOR MANUEL", 2, "P24546");
INSERT INTO profesor VALUES (24547,"ING. AGUILERA CRUZ JUAN CARLOS", 2, "P24547");
INSERT INTO profesor VALUES (24548,"ING GALLEGOS MUÑOZ LUIS ROBERTO", 2, "P24548");
INSERT INTO profesor VALUES (24549,"ING GARCIA ORNELAS DOMINGO", 2, "P24549");
INSERT INTO profesor VALUES (24550,"ING. SANDOVAL SOLIS MA. CONCEPCION", 2, "P24550");
INSERT INTO profesor VALUES (24551,"ING CASTILLO MARTÍNEZ PATRICIA MARIA", 2, "P24551");
INSERT INTO profesor VALUES (24552,"LIC TRUJILLO CASTELLANOS CARLOS ALBERTO", 2, "P24552");
INSERT INTO profesor VALUES (24553,"ING. GAMIÑO GUERRERO ADOLFO", 2, "P24553");
INSERT INTO profesor VALUES (24554,"ING. TAPIA IBARRA MA. VERONICA", 2, "P24554");
INSERT INTO profesor VALUES (24555,"ING. MURILLO RUIZ JUAN PABLO", 2, "P24555");
INSERT INTO profesor VALUES (24556,"ING. MANZANARES CUADROS JAVIER IVAN", 2, "P24556");
INSERT INTO profesor VALUES (24557,"M.C. LINO RAMIREZ CARLOS", 2, "P24557");
INSERT INTO profesor VALUES (24558,"ING. SUAREZ Y GOMEZ JOSE LUIS FERNANDO", 2, "P24558");
INSERT INTO profesor VALUES (24559,"ING. MARTINEZ PRADO EDNA MILITZA", 2, "P24559");

insert into horario (clave_materia, idprofesor, grupo, no_alum, salon, lunes, martes, miercoles, jueves, viernes) values ("SCD1003", 24557, "A", 20, "L-C2", "","7:00-8:40","", "7:00-8:40","")
